use anyhow::{Context, Result};
use argh::FromArgs;
use bidiff::DiffParams;
use crossbeam_utils::thread;
use log::*;
use memmap2::Mmap;
use size::Size;
use std::{
    fs::File,
    io::{self, BufReader, BufWriter, Write},
    path::PathBuf,
    time::Instant,
};

/// Generate and apply binary patches
#[derive(FromArgs, PartialEq, Debug)]
struct Cli {
    #[argh(subcommand)]
    cmd: Command,
}

#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand)]
enum Command {
    Diff(Diff),
    Patch(Patch),
    Cycle(Cycle),
}

/// Write the diff of two files to a patch file
#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand, name = "diff")]
struct Diff {
    #[argh(positional)]
    older: PathBuf,
    #[argh(positional)]
    newer: PathBuf,
    #[argh(positional)]
    patch: PathBuf,
    /// hash index block size (default 32, minimum 4)
    #[argh(option, default = "32")]
    block_size: usize,
    /// optionally specify a chunk size
    #[argh(option)]
    scan_chunk_size: Option<usize>,
}

/// Apply a patch file generated by this tool
#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand, name = "patch")]
struct Patch {
    #[argh(positional)]
    older: PathBuf,
    #[argh(positional)]
    patch: PathBuf,
    #[argh(positional)]
    output: PathBuf,
}

/// Cycle
#[derive(FromArgs, PartialEq, Debug)]
#[argh(subcommand, name = "cycle")]
struct Cycle {
    #[argh(positional)]
    older: PathBuf,
    #[argh(positional)]
    newer: PathBuf,
    /// hash index block size (default 32, minimum 4)
    #[argh(option, default = "32")]
    block_size: usize,
    /// optionally specify a chunk size
    #[argh(option)]
    scan_chunk_size: Option<usize>,
}

fn main() -> Result<()> {
    #[cfg(debug_assertions)]
    std::env::set_var("RUST_BACKTRACE", "1");

    env_logger::builder().init();

    let Cli { cmd } = argh::from_env();
    match cmd {
        Command::Diff(args) => {
            do_diff(&args)?;
        }
        Command::Patch(args) => {
            do_patch(&args)?;
        }
        Command::Cycle(args) => {
            do_cycle(&args)?;
        }
    }

    Ok(())
}

fn do_cycle(
    Cycle {
        older,
        newer,
        block_size,
        scan_chunk_size,
    }: &Cycle,
) -> Result<()> {
    info!("Memory-mapping older and newer...");
    let (older, newer) = (mmap_file(older)?, mmap_file(newer)?);

    info!(
        "Before {}, After {}",
        Size::from_bytes(older.len()),
        Size::from_bytes(newer.len()),
    );

    let mut compatch = Vec::new();
    let before_diff = Instant::now();

    {
        let mut compatch_w = io::Cursor::new(&mut compatch);

        let (mut patch_r, mut patch_w) = pipe::pipe();
        let diff_params = DiffParams::new(*block_size, *scan_chunk_size).unwrap();
        thread::scope(|s| {
            s.spawn(|_| {
                bidiff::simple_diff_with_params(&older[..], &newer[..], &mut patch_w, &diff_params)
                    .context("simple diff with params")
                    .unwrap();
                // this is important for `.compress()` to finish.
                // since we're using scoped threads, it's never dropped
                // otherwise.
                drop(patch_w);
            });
            zstd::stream::copy_encode(&mut patch_r, &mut compatch_w, 3)
                .context("compress")
                .unwrap();
        })
        .unwrap();
    }

    let diff_duration = before_diff.elapsed();

    let ratio = (compatch.len() as f64) / (newer.len() as f64);

    let mut fresh = Vec::new();
    let before_patch = Instant::now();
    {
        let mut older = io::Cursor::new(&older[..]);

        let (patch_r, patch_w) = pipe::pipe();

        thread::scope(|s| {
            s.spawn(|_| {
                zstd::stream::copy_decode(&compatch[..], patch_w)
                    .context("decompress")
                    .unwrap();
            });

            let mut r = bipatch::Reader::new(patch_r, &mut older)
                .context("read patch")
                .unwrap();
            let fresh_size = io::copy(&mut r, &mut fresh).unwrap();

            assert_eq!(fresh_size as usize, newer.len());
        })
        .unwrap();
    }
    let patch_duration = before_patch.elapsed();

    let newer_hash = hmac_sha256::Hash::hash(&newer[..]);
    let fresh_hash = hmac_sha256::Hash::hash(&fresh[..]);

    anyhow::ensure!(newer_hash == fresh_hash, "Hash mismatch!");

    let cp = format!("patch {}", Size::from_bytes(compatch.len()));
    let cr = format!(
        "{:03.3}% of {}",
        ratio * 100.0,
        Size::from_bytes(newer.len())
    );
    let cdd = format!("dtime {:?}", diff_duration);
    let cpd = format!("ptime {:?}", patch_duration);
    println!("{:12} {:20} {:27} {:20} {:20}", "zstd", cp, cr, cdd, cpd);

    Ok(())
}

fn do_patch(
    Patch {
        older,
        patch,
        output,
    }: &Patch,
) -> Result<()> {
    let start = Instant::now();

    let compatch_r = BufReader::new(File::open(patch).context("open patch file")?);
    let (patch_r, patch_w) = pipe::pipe();

    std::thread::spawn(move || {
        zstd::stream::copy_decode(compatch_r, patch_w)
            .context("decompress")
            .unwrap();
    });

    let older_r = File::open(older)?;
    let mut fresh_r = bipatch::Reader::new(patch_r, older_r).context("read patch")?;
    let mut output_w = BufWriter::new(File::create(output).context("create patch file")?);
    io::copy(&mut fresh_r, &mut output_w).context("write output file")?;

    info!("Completed in {:?}", start.elapsed());

    Ok(())
}

fn mmap_file(path: &PathBuf) -> Result<Mmap> {
    let file = File::open(path).with_context(|| format!("open {}", path.display()))?;
    unsafe { Mmap::map(&file) }.with_context(|| format!("mmap {}", path.display()))
}

fn do_diff(
    Diff {
        older,
        newer,
        patch,
        block_size,
        scan_chunk_size,
    }: &Diff,
) -> Result<()> {
    let start = Instant::now();

    let older_contents = mmap_file(older)?;
    let newer_contents = mmap_file(newer)?;

    let (mut patch_r, mut patch_w) = pipe::pipe();
    let diff_params = DiffParams::new(*block_size, *scan_chunk_size).unwrap();
    thread::scope(|s| {
        s.spawn(|_| {
            bidiff::simple_diff_with_params(
                &older_contents[..],
                &newer_contents[..],
                &mut patch_w,
                &diff_params,
            )
            .context("simple diff with params")
            .unwrap();
            drop(patch_w);
        });

        let mut compatch_w =
            BufWriter::new(File::create(patch).context("create patch file").unwrap());
        zstd::stream::copy_encode(&mut patch_r, &mut compatch_w, 3)
            .context("write output file")
            .unwrap();
        compatch_w
            .flush()
            .context("finish writing output file")
            .unwrap();
    })
    .unwrap();

    info!("Completed in {:?}", start.elapsed());

    Ok(())
}
